version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "00:25"
      timezone: America/Sao_Paulo
    groups:
       batch-update:
          patterns:
            - "*" 
