[tool.poetry]
name = "inventory-manager"
version = "0.1.0"
description = ""
authors = ["Thiago Benine <thiagobenine@gmail.com>"]
readme = "README.md"
packages = [{include = "inventory_manager"}]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.6.3"


[tool.poetry.group.dev.dependencies]
pytest = "^8.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
