from typing import Protocol

from src.domain.entities.item import Item


class ItemRepositoryInterface(Protocol):
    def find_item_by_name(self, item_name: str) -> Item | None: ...

    def find_items_by_names(self, items_names: list[str]) -> list[Item]: ...

    def get_all(self) -> list[Item]: ...

    def remove_item_by_name(self, item_name: str) -> None: ...

    def save(self, item: Item) -> None: ...

    def save_all(self, items: list[Item]) -> None: ...
